Alunos: Eduardo Philippe, Douglas Royer e Vítor Gabriel Eduardo

# PARTE 1: Algoritmo Naïve Bayes

Nesta primeira parte do Trabalho você irá aplicar o algoritmo de Naïve Bayes na base de dados de risco de crédito discutida em aula. Para isso você deve primeiramente importar as bibliotecas necessárias.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
# importe a base de dados de risco de crédito e nomeie com: dataset_risco_credito

dataset_risco_credito = pd.read_csv("dataset_risco_credito.csv")

In [ ]:
# imprima a base de dados para uma primeira avaliação dos dados

print(dataset_risco_credito)

        historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto


# 1 - Pré-Processamento dos dados

a) DIVISÃO DA BASE DE DADOS

Separe a base de dados dataset_risco_credito em:
 - variável x, com nome: X_risco_credito
 - classe y, com nome: y_risco_credito

DICA: você pode utilizar .iloc para selecionar as colunas da matriz e .values para converter para o numpy array.



In [ ]:
X_risco_credito = dataset_risco_credito.values[:,0:4]
Y_risco_credito = dataset_risco_credito.values[:,4]
#dataset_risco_credito.columns.to_list()
print(X_risco_credito)
print(Y_risco_credito)


[['ruim' 'alta' 'nenhuma' '0_15']
 ['desconhecida' 'alta' 'nenhuma' '15_35']
 ['desconhecida' 'baixa' 'nenhuma' '15_35']
 ['desconhecida' 'baixa' 'nenhuma' 'acima_35']
 ['desconhecida' 'baixa' 'nenhuma' 'acima_35']
 ['desconhecida' 'baixa' 'adequada' 'acima_35']
 ['ruim' 'baixa' 'nenhuma' '0_15']
 ['ruim' 'baixa' 'adequada' 'acima_35']
 ['boa' 'baixa' 'nenhuma' 'acima_35']
 ['boa' 'alta' 'adequada' 'acima_35']
 ['boa' 'alta' 'nenhuma' '0_15']
 ['boa' 'alta' 'nenhuma' '15_35']
 ['boa' 'alta' 'nenhuma' 'acima_35']
 ['ruim' 'alta' 'nenhuma' '15_35']]
['alto' 'alto' 'moderado' 'alto' 'baixo' 'baixo' 'alto' 'moderado' 'baixo'
 'baixo' 'alto' 'moderado' 'baixo' 'alto']


b) APLICAR LABEL ENCODER

Perceba que seus dados possuem atributos categóricos (string). Porém, para aplicar esses dados em um algoritmo de aprendizado você precisa transformá-lo em atributo numérico.

Como você pode resolver isso?

DICA: Veja o que é e como aplicar o Label Enconder em: https://youtu.be/nLKEkBAbpQo

In [ ]:
# Apresente o resultado do label enconder
from sklearn.preprocessing import LabelEncoder


label_fit_historia = LabelEncoder().fit(X_risco_credito[:, 0])
X_risco_credito[:, 0] = label_fit_historia.transform(X_risco_credito[:, 0]).astype('int')

label_fit_divida = LabelEncoder().fit(X_risco_credito[:, 1])
X_risco_credito[:, 1] = label_fit_divida.transform(X_risco_credito[:, 1]).astype('int')

label_fit_garantia = LabelEncoder().fit(X_risco_credito[:, 2])
X_risco_credito[:, 2] = label_fit_garantia.transform(X_risco_credito[:, 2]).astype('int')

label_fit_renda = LabelEncoder().fit(X_risco_credito[:, 3])
X_risco_credito[:, 3] = label_fit_renda.transform(X_risco_credito[:, 3]).astype('int')

label_fit_risco = LabelEncoder().fit(Y_risco_credito[:])
Y_risco_credito[:] = label_fit_risco.transform(Y_risco_credito[:])

print(X_risco_credito)
print(Y_risco_credito)



[[2 0 1 0]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 2]
 [1 1 0 2]
 [2 1 1 0]
 [2 1 0 2]
 [0 1 1 2]
 [0 0 0 2]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 2]
 [2 0 1 1]]
[0 0 2 0 1 1 0 2 1 1 0 2 1 0]


c) SALVAR O ARQUIVO PRÉ-PROCESSADO

In [ ]:
# como salvar o arquivo:
import pickle
with open('risco_credito.pkl', 'wb') as f:
  pickle.dump([X_risco_credito, Y_risco_credito], f)

# 2 - Algoritmo Naïve Bayes

In [ ]:
# importar da biblioteca sklearn o pacote Nayve Bayes
# utilizamos a distribuição estatística Gaussiana (classe GaussianNB) ou distribuição normal pois é mais usado para problemas genéricos
from sklearn.naive_bayes import GaussianNB

In [ ]:
# Criar o objeto Nayve Bayes
naiveb_risco_credito = GaussianNB()

a) TREINAR O ALGORITMO

Para treinar o algoritmo, você deve gerar a tabela de probabilidades. Para isso, você pode utilizar **.fit** para gerar a tabela.

DICA: O 1º parametro são os atributos/características (x) e o 2º parametro é a classe (y).

OBS: Não se preocupe, o algoritmo faz a correção laplaciana automaticamente :) .

In [ ]:
print(X_risco_credito)
print(Y_risco_credito)


naiveb_risco_credito.fit(X_risco_credito, Y_risco_credito.astype('int'))

[[2 0 1 0]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 2]
 [1 1 0 2]
 [2 1 1 0]
 [2 1 0 2]
 [0 1 1 2]
 [0 0 0 2]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 2]
 [2 0 1 1]]
[0 0 2 0 1 1 0 2 1 1 0 2 1 0]


GaussianNB()

b) FAZER A PREVISÃO

Utilize **.predict** para fazer a previsão realizada no exemplo em sala.

i) história boa, dívida alta, garantia nenhuma, renda > 35

ii) história ruim, dívida alta, garantia adequada, renda < 15

Verifique nos slides se seu resultado está correto!

In [ ]:
# utilize o atributo .classes_ para mostrar as classes utilizadas pelo algoritmo

# i) história boa, dívida alta, garantia nenhuma, renda > 35
# ii) história ruim, dívida alta, garantia adequada, renda < 15
X_risco_credito_test = np.array([['boa','alta','nenhuma','acima_35'], ['ruim','alta','adequada','0_15']])

X_risco_credito_test[:,0] = label_fit_historia.transform(X_risco_credito_test[:,0])
X_risco_credito_test[:,1] = label_fit_divida.transform(X_risco_credito_test[:,1])
X_risco_credito_test[:,2] = label_fit_garantia.transform(X_risco_credito_test[:,2])
X_risco_credito_test[:,3] = label_fit_renda.transform(X_risco_credito_test[:,3])
print(X_risco_credito_test)

Y_risco_credito_test = naiveb_risco_credito.predict(X_risco_credito_test.astype(int))
print(label_fit_risco.inverse_transform(Y_risco_credito_test))
print(naiveb_risco_credito.classes_)


[['0' '0' '1' '2']
 ['2' '0' '0' '0']]
['baixo' 'moderado']
[0 1 2]


In [ ]:
# utilize .class_count_ para contar quantos registros tem em cada classe
classes = naiveb_risco_credito.class_count_

print('Alto:', classes[0].astype(int))
print('Baixo:', classes[1].astype(int))
print('Moderado:', classes[2].astype(int))



Alto: 6
Baixo: 5
Moderado: 3
